### ISSUE TITLE
add active state with timer

### ISSUE THREAD

**Issue by jtarchie** [jtarchie/helloretro#3]

**Comment by jtarchie** [comment]
https://github.com/jtarchie/helloretro/assets/75184/eebe73d9-0add-4c89-aed6-744e7c808590

@anEXPer, there you go.

**Comment by jtarchie** [comment]
release in 541c9f5d6925cc3dc15efb3ca2d9148d76d719bc

**Comment by anEXPer** [comment]
Nice!
