### ISSUE TITLE
Action items column

### ISSUE THREAD

**Issue by jpmcb** [jtarchie/helloretro#5]
I think the old pong app had an "action items" column (or was it in the footer?) that you could put things to take action on latter: would love if this was brought back or if there was an option for it!

**Comment by jtarchie** [comment]
Current idea:

<img width="1689" alt="PNG image" src="https://github.com/jtarchie/helloretro/assets/75184/82557ab7-e42a-4489-b474-233037acb4de">

**Comment by jtarchie** [comment]
This requires a wide screen. On smaller screens, I'm trying to figure out.

**Comment by jtarchie** [comment]
<img width="595" alt="Screenshot 2024-03-25 at 8 15 03 PM" src="https://github.com/jtarchie/helloretro/assets/75184/889a9c67-0631-47e4-981b-b2f879ab5312">
<img width="1197" alt="Screenshot 2024-03-25 at 8 14 50 PM" src="https://github.com/jtarchie/helloretro/assets/75184/058a9853-089f-4d95-8f3d-5de4a91f932a">
<img width="2535" alt="Screenshot 2024-03-25 at 8 14 42 PM" src="https://github.com/jtarchie/helloretro/assets/75184/5f3382df-ad07-4ee0-8219-86a67a56b4a2">

Possible different responsive designs.

**Comment by jtarchie** [comment]
A version has been deployed.
